[package]
name = "lan_ips"
version = "0.1.0"
authors = ["ParkinWu <snowy_way@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.22.0"
ipnetwork = "0.14.0"

[lib]
name = "zen"
path = "src/lib.rs"
